/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Client.Client;
import java.awt.event.KeyEvent;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintStream;
import java.net.InetAddress;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ProgressMonitorInputStream;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ashpex
 */
public class ClientForm extends javax.swing.JFrame {

    private Client client = null;
    private Socket socket = null;
    String userName = "";
    Thread threadReadClient = null;
    Thread threadWriteClient = null;
    String nameFriend = "";
    private final int BUFFER_SIZE = 100;
    private static final int CHUNK_SIZE = 1024;

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public Socket getSocket() {
        return socket;
    }

    public void setSocket(Socket socket) {
        this.socket = socket;
    }

    /**
     * Creates new form FormClient
     *
     * @param ip
     * @param port
     * @param username
     */
    public ClientForm(InetAddress ip, int port, String username) throws IOException {
        initComponents();
        try {
            socket = new Socket(ip, 3200);
            userName = username;
            client = new Client(port, ip, username);
            readClient();
            sendInfoToServer();
            System.err.println("error");

        } catch (IOException e) {
            System.out.println("There'is some error");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sendMessage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        icon = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        messageForm = new javax.swing.JTextArea();
        selectEnter = new javax.swing.JCheckBox();
        sendFile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        userList = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        Account = new javax.swing.JMenu();
        info = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        groupChat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sendMessage.setBackground(new java.awt.Color(0, 153, 0));
        sendMessage.setForeground(new java.awt.Color(255, 255, 255));
        sendMessage.setText("Send");
        sendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageActionPerformed(evt);
            }
        });

        messageArea.setEditable(false);
        messageArea.setColumns(20);
        messageArea.setRows(5);
        jScrollPane1.setViewportView(messageArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        icon.setBackground(new java.awt.Color(204, 204, 0));
        icon.setText("Emoji");
        icon.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                iconComponentShown(evt);
            }
        });
        icon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconActionPerformed(evt);
            }
        });

        messageForm.setColumns(20);
        messageForm.setRows(5);
        messageForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                messageFormKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(messageForm);

        selectEnter.setText("Enter to send");
        selectEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectEnterActionPerformed(evt);
            }
        });

        sendFile.setText("Attach");
        sendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFileActionPerformed(evt);
            }
        });

        userList.setBackground(new java.awt.Color(242, 242, 242));
        userList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Accounts"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        userList.setSelectionBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        userList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        userList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(userList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(selectEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(sendFile, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(selectEnter)
                                    .addComponent(sendFile))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sendMessage)
                                    .addComponent(icon))))
                        .addGap(23, 23, 23)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        Account.setText("Account");

        info.setText("Info");
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        Account.add(info);

        logout.setText("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        Account.add(logout);

        jMenuBar1.add(Account);

        groupChat.setText("Group chat");
        jMenuBar1.add(groupChat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        try {
            exitClient();
        } catch (IOException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_logoutActionPerformed

    private void userListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userListMouseClicked
        int dong = userList.getSelectedRow();
        int[] cot = userList.getSelectedColumns();
        nameFriend = String.valueOf(userList.getValueAt(dong, 0));

    }//GEN-LAST:event_userListMouseClicked

    private void sendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFileActionPerformed
        if (nameFriend == "") {
            JOptionPane.showMessageDialog(null, "You didn't select a receiver!");
        } else {

            File f = null;
            DataOutputStream dos = null;
            //Scanner sc = null;

            JFileChooser fileChooser = new JFileChooser();
            FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Images", "jpg", "png");
            fileChooser.setFileFilter(imageFilter);
            fileChooser.setMultiSelectionEnabled(false);
            int x = fileChooser.showDialog(fileChooser, "Select File");
            String fpath = "";
            if (x == JFileChooser.APPROVE_OPTION) {
                fpath = fileChooser.getSelectedFile().getPath();
            }
            File file = new File(fpath);
            String fileName = file.getName();
            long fileSize = file.length();
            PrintStream out = null;
            try {

                String tmp ="SEND_FILE" + " " + fileName + " " + fileSize + " " + userName + " " + nameFriend;
                dos = new DataOutputStream(socket.getOutputStream());
                dos.writeUTF(tmp);
                writeFile(file, socket.getOutputStream());
                System.out.println("Finished sending " + file.getName() + " to server");
            } catch (IOException ex) {
                Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            messageArea.append("You sent file : " + fileName + " to " + nameFriend + "\n");

        }
    }//GEN-LAST:event_sendFileActionPerformed

    private void selectEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectEnterActionPerformed

    private void messageFormKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messageFormKeyPressed
        if (selectEnter.isSelected()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (nameFriend.equals("ALL")) {
                    writeClientAll();
                } else {
                    writeClientOneOne();
                }
            }
        }
    }//GEN-LAST:event_messageFormKeyPressed

    private void sendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageActionPerformed
        if (nameFriend.equals("ALL")) {
            writeClientAll();
        } else {
            writeClientOneOne();
        }
    }//GEN-LAST:event_sendMessageActionPerformed

    private void iconComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_iconComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_iconComponentShown

    private void iconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoActionPerformed
    
    private void writeFile(File file, OutputStream outStream) {
        //Tham Khao
        FileInputStream reader = null;
        try {
            reader = new FileInputStream(file);
            byte[] buffer = new byte[CHUNK_SIZE];
            int pos = 0;
            int bytesRead;
            while ((bytesRead = reader.read(buffer, 0, CHUNK_SIZE)) >= 0) {
                outStream.write(buffer, 0, bytesRead);
                outStream.flush();
                pos += bytesRead;
                System.out.println(pos + " bytes (" + bytesRead + " bytes read)");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException ex) {
                    Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }
    
     private void saveFile(File file, InputStream inStream) {
         //Tham Khao
        FileOutputStream fileOut = null;
        
        try {
            fileOut = new FileOutputStream(file);
            byte[] buffer = new byte[CHUNK_SIZE];
            int bytesRead;
            int pos = 0;
            while ((bytesRead = inStream.read(buffer, 0, CHUNK_SIZE)) > 0) {
                pos += bytesRead;
                System.out.println(pos + " bytes (" + bytesRead + " bytes read)");
                fileOut.write(buffer, 0, bytesRead);
                if(bytesRead <1024){
                    break;
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            if (fileOut != null) {
                try {
                    fileOut.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        System.out.println("Finished, filesize = " + file.length());
    }
    /**
     * @param args the command line arguments
     */
    private String sms = "";

    private void readClient() throws IOException {
        threadReadClient = new Thread() {
            @Override
            public void run() {
                DataInputStream dis = null;

                try {
                    dis = new DataInputStream(socket.getInputStream());
                    while (true) {
                        String sms = dis.readUTF();
                        System.out.println(sms);
                        StringTokenizer token = new StringTokenizer(sms);
                        String Format = token.nextToken();
                        System.out.println(Format);
                        switch (Format) {
                            case "UserOnl": {
                                List<String> listFiend = new ArrayList<String>();
                                client.setListFiend(listFiend);
                                while (token.hasMoreTokens()) {
                                    String user = token.nextToken();

                                    client.addFriend(user);

                                    updateOnlineUsersList();
                                }
                                break;
                            }
                            case "ChatOneOne": {
                                String userFriend = token.nextToken();
                                String nameUser = token.nextToken();
                                String smsReceive = userFriend + " : ";

                                sms = sms.replaceAll(nameUser, "");
                                sms = sms.replaceAll(userFriend, "");
                                sms = sms.replaceAll("ChatOneOne", "");

                                messageArea.append(userFriend + " : " + sms + "\n");
                                System.out.println("write list of messages");
                                break;

                            }
                            case "ChatAll": {
                                String userFriend = token.nextToken();
                                sms = sms.replaceAll(userFriend, "");
                                sms = sms.replaceAll("ChatAll", "");
                                messageArea.append(userFriend + " chat to all:" + sms + "\n");
                                break;

                            }
                            case "SEND_FILE": {
                                String fileName = token.nextToken();
                                String stFileSize = token.nextToken();
                                String userSend = token.nextToken();
                                String userReceive = token.nextToken();

                                File file = new File("./files/",fileName);
                                saveFile(file, socket.getInputStream());
                                
                                messageArea.append(userSend + " sent a file: " + fileName + ". Please check your folder\n");
                                break;
                            }
                            default:
                                messageArea.append(sms + "\n");

                        }

                    }
                } catch (IOException ex) {
                    Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
                    try {
                        dis.close();
                        socket.close();
                    } catch (IOException ex1) {
                        Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex1);
                    }

                }

            }
        };
        threadReadClient.start();

    }
    
    

    private void writeClientAll() {
        Thread thread = new Thread() {
            @Override
            public void run() {
                DataOutputStream dos = null;
                //Scanner sc = null;
                try {
                    dos = new DataOutputStream(socket.getOutputStream());
                    sms = "ChatAll";
                    String tmp = messageForm.getText();
                    if (selectEnter.isSelected()) {
                        tmp = tmp.replaceAll("\n", "");
                    }
                    messageArea.append("Chat to all: " + tmp + "\n");
                    
                    sms = sms + " " + userName + " " + tmp;
                    
                    if (!sms.equals("")) {
                        dos.writeUTF(sms);
                        sms = "";
                        messageForm.setText("");
                    }
                    
                } catch (IOException ex) {
                    Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
                    try {
                        dos.close();
                        socket.close();
                    } catch (IOException ex1) {
                        Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex1);
                    }
                }
            }
        };
        thread.start();
    }

    private void writeClientOneOne() {
        Thread thread = new Thread() {
            @Override
            public void run() {
                DataOutputStream dos = null;
                //Scanner sc = null;
                try {
                    dos = new DataOutputStream(socket.getOutputStream());
                    sms = "ChatOneOne";
                    String tmp = messageForm.getText();
                    if (selectEnter.isSelected()) {
                        tmp = tmp.replaceAll("\n", "");
                    }
                    sms = sms + " " + userName + " " + nameFriend + " " + tmp;

                    if (!sms.equals("")) {
                        dos.writeUTF(sms);
                        sms = "";
                        messageForm.setText("");
                    }

                    messageArea.append("You messaged " + nameFriend + ": " + tmp + "\n");
                } catch (IOException ex) {
                    Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
                    try {
                        dos.close();
                        socket.close();
                    } catch (IOException ex1) {
                        Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex1);
                    }
                }
            }
        };
        thread.start();
    }

    private void sendInfoToServer() {
        Thread thread = new Thread() {
            @Override
            public void run() {
                DataOutputStream dos = null;
                //Scanner sc = null;
                try {
                    dos = new DataOutputStream(socket.getOutputStream());
                    String info = "Info" + " " + userName;
                    dos.writeUTF(info);

                } catch (IOException ex) {
                    Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
                    try {
                        dos.close();
                        socket.close();
                    } catch (IOException ex1) {
                        Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex1);
                    }
                }
            }

        };
        thread.start();
    }

    private void execute() throws IOException {
        readClient();
        //writeClient();
    }

    private void updateOnlineUsersList() {
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        userList.setModel(defaultTableModel);
        defaultTableModel.addColumn("Online accounts");
        List<String> danhSachOnl = client.getListFiend();
        for (String i : danhSachOnl) {
            Object[] tmp = new Object[]{i};
            defaultTableModel.addRow(tmp);
        }
        defaultTableModel.addRow(new Object[]{"ALL"});
    }

    private void exitClient() throws IOException {
        Thread thread = new Thread() {
            @Override
            public void run() {
                DataOutputStream dos = null;
                //Scanner sc = null;
                try {
                    dos = new DataOutputStream(socket.getOutputStream());
                    String info = "Exit" + " " + userName;
                    dos.writeUTF(info);

                    threadReadClient.stop();
                    if (threadWriteClient != null) {
                        threadWriteClient.stop();
                    }
                    socket.close();
                } catch (IOException ex) {
                    Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
                    try {
                        dos.close();

                        socket.close();
                    } catch (IOException ex1) {
                        Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex1);
                    }
                }
            }

        };
        thread.start();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Account;
    private javax.swing.JMenu groupChat;
    private javax.swing.JButton icon;
    private javax.swing.JMenuItem info;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem logout;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JTextArea messageForm;
    private javax.swing.JCheckBox selectEnter;
    private javax.swing.JButton sendFile;
    private javax.swing.JButton sendMessage;
    private javax.swing.JTable userList;
    // End of variables declaration//GEN-END:variables
}
